Support compatibility tools other than Proton out-of-the-box.
Open-Wine-Components/ULWGL pull request #293
Opened 2024-11-29 19:21 UTC by loathingKernel

Marked as draft for now pending the first round of reviews.

2024-12-06 11:41 UTC, beh-10257 commented
will this make it possible to use proton-tkg ??
sorry if this is early days

2024-12-06 11:47 UTC, loathingKernel commented
> will this make it possible to use proton-tkg ?? sorry if this is early days

It should make possible to run any tool that works with Steam, as a compatibility tool. The main constraint not addressed yet are tools that require a runtime other than `sniper` but I consider support for multiple runtimes a superset which is not going to be addressed by this PR alone.

2025-01-06 02:49 UTC, R1kaB3rN commented
Yeah I guess it all boils down to whether supporting more compatibility tools is something we want to support, and all think will be very useful to enable for users.  Right now, I’m observing users are satisfied with the experience of just running their games through Proton. I haven’t seen any reports/stories of users/clients wanting more than that, unless you can bring up a few cases where they did? So I would kind of like to have more folks chime in with their thoughts, and maybe wait a bit. 

Utility aside, in the case of winetricks, I think this would allow us to take out the winetricks code we have in both umu and Proton, and make it a tool instead. That architectural change, sorta makes it attractive but at the cost of some parsing overhead and introducing another point a failure at launch for something we don’t directly control (yet). On the other hand, we could just make the tools native properties of the runtime. This avoids the mess of parsing and figuring out the correct runtime all together. If the tool isn’t large as Proton, it should be a problem. 

Also, on the topic of compat tools, I actually view supporting only 2 compatibility tools (SLR and Proton) as an advantage we have over Steam, which has to deal with the backward compatibility hell. Hence, they continue (and will forever) to support/keep obsolete runtimes and come up with solutions like nesting scout in soldier. With umu, we have the opportunity to avoid some of those decisions and come up with better solutions instead for certain areas. To me, I think keeping it simple by maintaining 1 runtime, while keeping but not updating old ones, and running both Linux/Windows executables is one of those areas.

2025-01-06 10:56 UTC, loathingKernel commented
>  Right now, I’m observing users are satisfied with the experience of just running their games through Proton. I haven’t seen any reports/stories of users/clients wanting more than that, unless you can bring up a few cases where they did?

A few I can gather from different projects are below. I am pinging @imLinguin since they also have expressed interest in this feature and they could provide more use-cases.
[Boxtron in Heroic](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/3793)
[Luxtorpeda in Rare}(https://github.com/RareDevs/Rare/issues/275)
[Proton-CachyOS with Lutris](https://wiki.cachyos.org/configuration/gaming/#how-can-i-setup-umu-launcher-with-proton-cachyos-in-lutris)

> and maybe wait a bit.

Certainly because this is an invasive architectural change if we want to do it properly and should be done in a way that makes sense for everyone.

> Utility aside, in the case of winetricks, I think this would allow us to take out the winetricks code we have in both umu and Proton, and make it a tool instead.

This is indeed an interesting proposition, but I have not considered it yet, simply because `winetricks` is inherently tied to proton and wine. It does require of a wine to be present in the process and to me that is simpler to exist as it does now, a script provided by `umu-protonfixes`.

> On the other hand, we could just make the tools native properties of the runtime. This avoids the mess of parsing and figuring out the correct runtime all together. If the tool isn’t large as Proton, it shouldn’t be a problem.

I do not agree with where this proposition is headed. I do not think we should alienate external tools or confuse the users with home-brew alternatives for things they already might be using. For me umu's mission is to unify what already exists for Steam, and make it available for other launchers, not be yet another choice clustering the space even more. For better or worse, it does tie umu to parsing and using the same attributes that Steam uses, but that's what it does already in other regards.

> Also, on the topic of compat tools, I actually view supporting only 2 compatibility tools (SLR and Proton) as an advantage we have over Steam, which has to deal with the backward compatibility hell. Hence, they continue (and will forever) to support/keep obsolete runtimes and come up with solutions like nesting scout in soldier. With umu, we have the opportunity to avoid some of those decisions and come up with better solutions instead for certain areas. To me, I think keeping it simple by maintaining 1 runtime, while keeping but not updating old ones, and running both Linux/Windows executables is one of those areas.

@imLinguin has demonstrated some interesting aspects of `scout-on-soldier` already by using it to run older native game from GOG, thus such an effort brings forth an opportunity to be useful towards those stores in keeping their existing native ports usable.

Another example is, IIRC, Helldivers which was not playable on recent proton versions but required some old version which was based on `soldier` to run. Using that version is not currently possible with `umu` due to different runtime requirements. Similarly this is likely to happen once `medic` starts rolling out.

Overall I do not consider constraining umu to two compatiblity tools beneficial, and since the difficult part of maintaining these runtimes doesn't fall on umu, I would consider it a net gain.

2025-01-21 10:28 UTC, loathingKernel commented
Currently this PR assumes the following structure. In the following diagram `<umu_share>` refers to `~/.local/share/umu`, and the links are for their downloads

```
<umu_share>/scout : 
        https://repo.steampowered.com/pressure-vessel/snapshots/latest/app1070560/SteamLinuxRuntime.tar.xz
<umu_share>/scout/steam-runtime : 
        https://repo.steampowered.com/steamrt1/images/latest-public-beta/steam-runtime.tar.xz
<umu_share>/scout/steam-runtime .tar.xz.checksum :
        https://repo.steampowered.com/steamrt1/images/latest-public-beta/steam-runtime.tar.xz.checksum

<umu_share>/soldier : 
        https://repo.steampowered.com/steamrt2/images/latest-container-runtime-public-beta/SteamLinuxRuntime_soldier.tar.xz

<umu_share>/sniper : 
        Sniper is currently used from the existing sniper installation in <umu_share> through overrides.
```

To quickly test by constructing the expected folder/file structure copied from a Steam installation
```sh
cp ~/.local/share/Steam/steamapps/common/SteamLinuxRuntime ~/.local/share/umu/scout -r
cp ~/.local/share/Steam/ubuntu12_32/steam-runtime ~/.local/share/umu/scout/ -r
cp ~/.local/share/Steam/ubuntu12_32/steam-runtime.tar.xz.checksum ~/.local/share/umu/scout/ -r
cp ~/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/ ~/.local/share/umu/soldier -r
```

To run an application with `scout-on-soldier`
```sh
UMU_LOG=1 GAMEID=0 WINEPREFIX=~/Wine/umu/ PROTONPATH=scout umu-run <app>
```

2025-04-08 20:49 UTC, MattSturgeon reviewed
I noticed the nix package is failing to build, because you've added a new vendored dependency.

You'll need to add a configure flag to allow disabling this, and update the nix package to get vdf from nixpkgs.

I've added some inline comments with patches, but the full diff is in this comment.

<details><summary>Full patch</summary>
<p>

```diff
diff --git a/Makefile.in b/Makefile.in
index 130e3f2..8e8a7ef 100644
--- a/Makefile.in
+++ b/Makefile.in
@@ -23,6 +23,7 @@ FLATPAK ?= xfalse
 # Ex. Arch and Fedora have pyzstd but ubuntu and debian don't
 USE_SYSTEM_PYZSTD ?= xfalse
 USE_SYSTEM_URLLIB ?= xfalse
+USE_SYSTEM_VDF ?= xfalse
 
 INSTALLER_ARGS := -m installer $(OBJDIR)/umu_launcher*.whl
 ifdef DESTDIR
@@ -118,7 +119,9 @@ $(OBJDIR)/.build-umu-vendored: | $(OBJDIR)
 		sed -i 's/setuptools>=64,<74/setuptools/' subprojects/pyzstd/pyproject.toml; \
 		cd subprojects/pyzstd && $(PYTHON_INTERPRETER) -m build -wn --outdir=$(OBJDIR); \
 	fi
-	cd subprojects/vdf && $(PYTHON_INTERPRETER) -m build -wn --outdir=$(OBJDIR)
+	@if [ "$(USE_SYSTEM_VDF)" != "xtrue" ]; then \
+		cd subprojects/vdf && $(PYTHON_INTERPRETER) -m build -wn --outdir=$(OBJDIR); \
+	fi
 	@if [ "$(USE_SYSTEM_URLLIB)" != "xtrue" ]; then \
 		cd subprojects/urllib3 && $(PYTHON_INTERPRETER) -m build -wn --outdir=$(OBJDIR); \
 	fi
@@ -134,8 +137,10 @@ umu-vendored-install: umu-vendored
 		$(PYTHON_INTERPRETER) -m installer --destdir=$(DESTDIR)$(PYTHONDIR)/umu/_vendor subprojects/pyzstd/$(OBJDIR)/pyzstd*.whl; \
 		find $(DESTDIR)$(PYTHONDIR)/umu/_vendor -type d -name pyzstd | xargs -I {} mv {} $(DESTDIR)$(PYTHONDIR)/umu/_vendor; \
 	fi
-	$(PYTHON_INTERPRETER) -m installer --destdir=$(DESTDIR)$(PYTHONDIR)/umu/_vendor subprojects/vdf/$(OBJDIR)/vdf*.whl
-	find $(DESTDIR)$(PYTHONDIR)/umu/_vendor -type d -name vdf | xargs -I {} mv {} $(DESTDIR)$(PYTHONDIR)/umu/_vendor
+	@if [ "$(USE_SYSTEM_VDF)" != "xtrue" ]; then \
+		$(PYTHON_INTERPRETER) -m installer --destdir=$(DESTDIR)$(PYTHONDIR)/umu/_vendor subprojects/vdf/$(OBJDIR)/vdf*.whl; \
+		find $(DESTDIR)$(PYTHONDIR)/umu/_vendor -type d -name vdf | xargs -I {} mv {} $(DESTDIR)$(PYTHONDIR)/umu/_vendor; \
+	fi
 	@if [ "$(USE_SYSTEM_URLLIB)" != "xtrue" ]; then \
 		$(PYTHON_INTERPRETER) -m installer --destdir=$(DESTDIR)$(PYTHONDIR)/umu/_vendor subprojects/urllib3/$(OBJDIR)/urllib3*.whl; \
 		find $(DESTDIR)$(PYTHONDIR)/umu/_vendor -type d -name urllib3 | xargs -I {} mv {} $(DESTDIR)$(PYTHONDIR)/umu/_vendor; \
diff --git a/configure.sh b/configure.sh
index 27d3efd..f5ecd93 100755
--- a/configure.sh
+++ b/configure.sh
@@ -75,6 +75,9 @@ function configure() {
     if [[ -n "$arg_use_system_urllib" ]]; then
       echo "USE_SYSTEM_URLLIB := xtrue"
     fi
+    if [[ -n "$arg_use_system_vdf" ]]; then
+      echo "USE_SYSTEM_VDF := xtrue"
+    fi
 
     # Prefix was specified, baking it into the Makefile
     if [[ -n $arg_prefix ]]; then
@@ -98,6 +101,7 @@ arg_user_install=""
 arg_help=""
 arg_use_system_pyzstd=""
 arg_use_system_urllib=""
+arg_use_system_vdf=""
 function parse_args() {
   local arg;
   local val;
@@ -147,6 +151,8 @@ function parse_args() {
       arg_use_system_pyzstd="1"
     elif [[ $arg = --use-system-urllib ]]; then
       arg_use_system_urllib="1"
+    elif [[ $arg = --use-system-vdf ]]; then
+      arg_use_system_vdf="1"
     else
       err "Unrecognized option $arg"
       return 1
diff --git a/packaging/nix/unwrapped.nix b/packaging/nix/unwrapped.nix
index c9f6006..f1b0d4c 100644
--- a/packaging/nix/unwrapped.nix
+++ b/packaging/nix/unwrapped.nix
@@ -3,6 +3,7 @@
   callPackage,
   lib,
   rustPlatform,
+  python3Packages,
   umu-launcher-unwrapped,
   version,
   # Freeform overrides
@@ -14,6 +15,7 @@
     "callPackage"
     "lib"
     "rustPlatform"
+    "python3Packages"
     "umu-launcher-unwrapped"
     "version"
   ];
@@ -36,13 +38,25 @@
     then umu-launcher-unwrapped
     else umu-launcher-unwrapped.override overrideArgs;
 in
-  package.overridePythonAttrs {
+  package.overridePythonAttrs (old: {
     inherit version;
     src = ../../.;
     cargoDeps = rustPlatform.importCargoLock {
       lockFile = ../../Cargo.lock;
     };
 
+    pythonPath =
+      (old.pythonPath or [])
+      ++ [
+        python3Packages.vdf
+      ];
+
+    configureFlags =
+      (old.configureFlags or [])
+      ++ [
+        "--use-system-vdf"
+      ];
+
     # Specify ourselves which tests are disabled
     disabledTests = [
       # Broken? Asserts that $STEAM_RUNTIME_LIBRARY_PATH is non-empty
@@ -53,5 +67,14 @@ in
       # Broken? Tests parse_args with no options (./umu_run.py)
       # Fails with AssertionError: SystemExit not raised
       "test_parse_args_noopts"
+
+      # FileNotFoundError: [Errno 2] No such file or directory: .local/share/umu/toolmanifest.vdf
+      "test_build_command"
+      "test_build_command_linux_exe"
+      "test_build_command_nopv"
+
+      # TypeError: cannot unpack non-iterable ThreadPoolExecutor object
+      "test_env_nowine_noproton"
+      "test_env_wine_noproton"
     ];
-  }
+  })
```

</p>
</details>

With the above patch, I was able to build the nix package locally.

It's a little concerning that some tests needed to be disabled for it though. This could be due to running the tests within the nix build sandbox, or it could be a genuine bug.

2025-04-08 20:49 UTC, MattSturgeon commented on .gitmodules
> +	url = https://github.com/ValvePython/vdf.git
The nix build is failing because it's trying to build the vendored dependency.

It looks like vdf is packaged in nixpkgs, so you can update the nix package as follows:

<details><summary>Patch</summary>
<p>

```diff
diff --git a/packaging/nix/package.nix b/packaging/nix/package.nix
index 2030f87..b1572b5 100644
--- a/packaging/nix/package.nix
+++ b/packaging/nix/package.nix
@@ -41,5 +41,9 @@ in
         if overrides == {}
         then umu-launcher-unwrapped
         else umu-launcher-unwrapped.override overrides;
+
+      extraPkgs = pkgs: [
+        pkgs.util-linux
+      ];
     }
   )
diff --git a/packaging/nix/unwrapped.nix b/packaging/nix/unwrapped.nix
index c9f6006..5568ea3 100644
--- a/packaging/nix/unwrapped.nix
+++ b/packaging/nix/unwrapped.nix
@@ -3,6 +3,7 @@
   callPackage,
   lib,
   rustPlatform,
+  python3Packages,
   umu-launcher-unwrapped,
   version,
   # Freeform overrides
@@ -14,6 +15,7 @@
     "callPackage"
     "lib"
     "rustPlatform"
+    "python3Packages"
     "umu-launcher-unwrapped"
     "version"
   ];
@@ -36,13 +38,25 @@
     then umu-launcher-unwrapped
     else umu-launcher-unwrapped.override overrideArgs;
 in
-  package.overridePythonAttrs {
+  package.overridePythonAttrs (old: {
     inherit version;
     src = ../../.;
     cargoDeps = rustPlatform.importCargoLock {
       lockFile = ../../Cargo.lock;
     };
 
+    pythonPath =
+      (old.pythonPath or [])
+      ++ [
+        python3Packages.vdf
+      ];
+
+    configureFlags =
+      (old.configureFlags or [])
+      ++ [
+        "--use-system-vdf"
+      ];
+
     # Specify ourselves which tests are disabled
     disabledTests = [
       # Broken? Asserts that $STEAM_RUNTIME_LIBRARY_PATH is non-empty
@@ -54,4 +68,4 @@ in
       # Fails with AssertionError: SystemExit not raised
       "test_parse_args_noopts"
     ];
-  }
+  })
```

</p>
</details> 

Looks like you also need to disable some tests for nix. Some may be real failures though, so maybe worth investigating?

<details><summary>Patch</summary>
<p>

```diff
diff --git a/packaging/nix/unwrapped.nix b/packaging/nix/unwrapped.nix
index 5568ea3..f1b0d4c 100644
--- a/packaging/nix/unwrapped.nix
+++ b/packaging/nix/unwrapped.nix
@@ -67,5 +67,14 @@ in
       # Broken? Tests parse_args with no options (./umu_run.py)
       # Fails with AssertionError: SystemExit not raised
       "test_parse_args_noopts"
+
+      # FileNotFoundError: [Errno 2] No such file or directory: .local/share/umu/toolmanifest.vdf
+      "test_build_command"
+      "test_build_command_linux_exe"
+      "test_build_command_nopv"
+
+      # TypeError: cannot unpack non-iterable ThreadPoolExecutor object
+      "test_env_nowine_noproton"
+      "test_env_wine_noproton"
     ];
   })
```

</p>
</details> 

However, you will need to add a `--use-system-vdf` flag to the configure script, similar to the existing `--use-system-pyzstd` and `--use-system-urllib` flags:

<details><summary>Patch</summary>
<p>

```diff
diff --git a/configure.sh b/configure.sh
index 27d3efd..f5ecd93 100755
--- a/configure.sh
+++ b/configure.sh
@@ -75,6 +75,9 @@ function configure() {
     if [[ -n "$arg_use_system_urllib" ]]; then
       echo "USE_SYSTEM_URLLIB := xtrue"
     fi
+    if [[ -n "$arg_use_system_vdf" ]]; then
+      echo "USE_SYSTEM_VDF := xtrue"
+    fi
 
     # Prefix was specified, baking it into the Makefile
     if [[ -n $arg_prefix ]]; then
@@ -98,6 +101,7 @@ arg_user_install=""
 arg_help=""
 arg_use_system_pyzstd=""
 arg_use_system_urllib=""
+arg_use_system_vdf=""
 function parse_args() {
   local arg;
   local val;
@@ -147,6 +151,8 @@ function parse_args() {
       arg_use_system_pyzstd="1"
     elif [[ $arg = --use-system-urllib ]]; then
       arg_use_system_urllib="1"
+    elif [[ $arg = --use-system-vdf ]]; then
+      arg_use_system_vdf="1"
     else
       err "Unrecognized option $arg"
       return 1
```

</p>
</details> 

Your changes in the makefile would also need to check `USE_SYSTEM_VDF`.

2025-04-08 20:49 UTC, MattSturgeon commented on Makefile.in
> +
Unrelated blank line?
```suggestion
```

2025-04-08 20:49 UTC, MattSturgeon commented on Makefile.in
You need to make the vdf build conditional:

<details><summary>Patch</summary>
<p>

```diff
diff --git a/Makefile.in b/Makefile.in
index 130e3f2..8e8a7ef 100644
--- a/Makefile.in
+++ b/Makefile.in
@@ -23,6 +23,7 @@ FLATPAK ?= xfalse
 # Ex. Arch and Fedora have pyzstd but ubuntu and debian don't
 USE_SYSTEM_PYZSTD ?= xfalse
 USE_SYSTEM_URLLIB ?= xfalse
+USE_SYSTEM_VDF ?= xfalse
 
 INSTALLER_ARGS := -m installer $(OBJDIR)/umu_launcher*.whl
 ifdef DESTDIR
@@ -118,7 +119,9 @@ $(OBJDIR)/.build-umu-vendored: | $(OBJDIR)
 		sed -i 's/setuptools>=64,<74/setuptools/' subprojects/pyzstd/pyproject.toml; \
 		cd subprojects/pyzstd && $(PYTHON_INTERPRETER) -m build -wn --outdir=$(OBJDIR); \
 	fi
-	cd subprojects/vdf && $(PYTHON_INTERPRETER) -m build -wn --outdir=$(OBJDIR)
+	@if [ "$(USE_SYSTEM_VDF)" != "xtrue" ]; then \
+		cd subprojects/vdf && $(PYTHON_INTERPRETER) -m build -wn --outdir=$(OBJDIR); \
+	fi
 	@if [ "$(USE_SYSTEM_URLLIB)" != "xtrue" ]; then \
 		cd subprojects/urllib3 && $(PYTHON_INTERPRETER) -m build -wn --outdir=$(OBJDIR); \
 	fi
@@ -134,8 +137,10 @@ umu-vendored-install: umu-vendored
 		$(PYTHON_INTERPRETER) -m installer --destdir=$(DESTDIR)$(PYTHONDIR)/umu/_vendor subprojects/pyzstd/$(OBJDIR)/pyzstd*.whl; \
 		find $(DESTDIR)$(PYTHONDIR)/umu/_vendor -type d -name pyzstd | xargs -I {} mv {} $(DESTDIR)$(PYTHONDIR)/umu/_vendor; \
 	fi
-	$(PYTHON_INTERPRETER) -m installer --destdir=$(DESTDIR)$(PYTHONDIR)/umu/_vendor subprojects/vdf/$(OBJDIR)/vdf*.whl
-	find $(DESTDIR)$(PYTHONDIR)/umu/_vendor -type d -name vdf | xargs -I {} mv {} $(DESTDIR)$(PYTHONDIR)/umu/_vendor
+	@if [ "$(USE_SYSTEM_VDF)" != "xtrue" ]; then \
+		$(PYTHON_INTERPRETER) -m installer --destdir=$(DESTDIR)$(PYTHONDIR)/umu/_vendor subprojects/vdf/$(OBJDIR)/vdf*.whl; \
+		find $(DESTDIR)$(PYTHONDIR)/umu/_vendor -type d -name vdf | xargs -I {} mv {} $(DESTDIR)$(PYTHONDIR)/umu/_vendor; \
+	fi
 	@if [ "$(USE_SYSTEM_URLLIB)" != "xtrue" ]; then \
 		$(PYTHON_INTERPRETER) -m installer --destdir=$(DESTDIR)$(PYTHONDIR)/umu/_vendor subprojects/urllib3/$(OBJDIR)/urllib3*.whl; \
 		find $(DESTDIR)$(PYTHONDIR)/umu/_vendor -type d -name urllib3 | xargs -I {} mv {} $(DESTDIR)$(PYTHONDIR)/umu/_vendor; \
```

</p>
</details>

2025-04-08 22:04 UTC, loathingKernel commented
Thank you for the review and the patches. I will be applying them shortly.

> It's a little concerning that some tests needed to be disabled for it though. This could be due to running the tests within the nix build sandbox, or it could be a genuine bug.

This is "expected" as due to the age of this PR it has been rebased a few times and I will have look into updating the tests again once I have finished with the changes. This PR is in need of rebasing again, I should probably revert it to a draft again. I would like to not disable the tests as it is as they reflect the state of the PR. Does this PR failing block anything related to NixOS packaging as it stands?

2025-04-08 22:24 UTC, loathingKernel commented on Makefile.in
> +
intended change for easier visual grouping

2025-04-08 22:28 UTC, MattSturgeon commented
> Does this PR failing block anything related to NixOS packaging as it stands?

No, I only noticed when testing on your branch locally. It'll only be an issue once merged, but if CI is green then all's good.

Running the test suite is part of the nix package's build process, so if a test fails the package also fails.

Some tests can't be run during the nix package's build though, because the build is done within a restricted sandbox (e.g. networking is disabled in the sandbox). So it's common to have a few tests disabled.

2025-09-10 11:32 UTC, loathingKernel commented
This PR also contains the beginnings of what could be used to resolve https://github.com/Open-Wine-Components/umu-launcher/issues/283 . Presently it is looking for `wineserver` to figure out the namespace of the process it has to interact with. A more generic solution, one that also works for non-proton applications should be available through https://github.com/Open-Wine-Components/umu-launcher/pull/497, by looking for the "internal" `reaper` the aforementioned PR provides.

2025-11-18 19:23 UTC, loathingKernel commented
Changed the way to re-enter the container to use `steam-runtime-tools` instead of `nsenter`. The differentiating factor between when the container should be re-entered and when a new instance should be started boils down to the path of the prefix. This assumes that at any given time only one container/proton should operate on a prefix.

This is now doing what I wanted it to do. I am opening it to reviews. I'll write tests after any refactors and issue fixes have concluded.

2025-11-21 11:29 UTC, loathingKernel commented
Updated description

2025-11-22 02:26 UTC, R1kaB3rN requested changes

2025-11-22 02:26 UTC, R1kaB3rN commented on docs/umu.1.scd
Writing some thoughts here because I want to block this pull request before merge and I don't know anywhere else to write it.

---

Alright, so in regards to the interface, let's not overload `PROTONPATH`. For example:
```
GAMEID=0 WINEPREFIX=~/Wine/umu/ UMU_LOG=debug PROTONPATH=umu-scout umu-run xterm
```
Users currently expect the value to be associated with Proton, not a token like `umu-scout`. Instead, let's create a new environment variable like `TOOLPATH` , where it's just a path to some directory with a vdf file and the compatibility tool's files. In the docs, add `TOOLPATH` to a debugging section.

2025-11-22 02:27 UTC, R1kaB3rN requested changes

2025-11-22 02:27 UTC, R1kaB3rN commented on docs/umu.1.scd
> +_UMU_NO_RUNTIME_
For this, please create a dedicated debugging section in our docs and add this environment variable within its block.

2025-11-22 02:35 UTC, R1kaB3rN commented on packaging/nix/unwrapped.nix
> +  python3Packages,
Let's not worry about the Flake for now. Same for the changes to `umu_plugins.py`.

Packaging in particular is non-urgent and can revisit to fix it up any time. I'd like to focus on this feature.

2025-11-22 02:42 UTC, R1kaB3rN requested changes

2025-11-22 02:42 UTC, R1kaB3rN commented on umu/umu_proton.py
> +import vdf
I want to add the module to this project as a file to this project instead as a submodule.

Like python-xlib, the developer of that project does not maintain that library anymore. It's only ~700 lines of Python code and by adding the file, we can competently maintain the code ourselves, improve its quality (e.g., add type annotations, drop the python 2 compatibility, etc.), and address any bugs found. The project license (MIT) permits that for us.

2025-11-22 03:28 UTC, R1kaB3rN commented
In regards to the feature's implementation, I believe we can achieve generic compatibility tool support in umu with a lot less changes throughout the codebase

At a high level, basically, umu-launcher just needs to:

1. Read the compatibility tool's VDF text file. Namely, right now, manifest v1 and manifest v2.
2. Resolve its required tool app IDs, if any.
3.  Download the required tool app IDs and install it, if not already installed and if any.
4. Go back to step 1, if needed.
5. Build the correct command line chain that is derived from the VDF text file(s).

Something like that, right? But given the current code, I can imagine what the challenges would be. I will have to explore this further.

2025-11-22 07:52 UTC, loathingKernel commented on docs/umu.1.scd
> +_UMU_NO_RUNTIME_
I think I will just remove this section, nothing  that options does relevant is relevant to this PR any more.

2025-11-22 07:55 UTC, loathingKernel commented on umu/umu_proton.py
> +import vdf
There's also this updated fork <https://github.com/solsticegamestudios/vdf> . I don't mind it either way, let me know why one to include.

2025-11-22 08:07 UTC, loathingKernel commented on docs/umu.1.scd
I think that users who use umu directly will be unaffected, and launchers using umu will be appreciative that we are not introducing another env variable with the same function basically. We can create another env variable, but I would prefer it to operate identically to `PROTONPATH`, one being an alias of the other. If we want to artificially separate them, imo it should be done when parsing them and not on how they operate.

Why do you think it should be a path? That's what confusing me. `umu-scout` is a tool that gets downloaded and managed by umu, it lives under `~/.local/share/umu/compatibilitytools`, and eventually can be automatically updated.

I am not sure I understand to be honest, is the issue solely with the name of the env variable being expanded, which ok, I can see it, or with how it operates?

2025-11-22 08:52 UTC, loathingKernel commented
> I believe we can achieve generic compatibility tool support in umu with a lot less changes throughout the codebase

Not if you want it done correctly, in that case the changes are not extensive enough. This is not just generic compatibility tools support, this is about supporting runtime chains for whatever runtimes Valve might release in the future. Currently this is capped at two-layer chains because of some of umu's assumptions, but the changes introduced here are agnostic to the depth of the runtime chain. If there is a specific issue where something can be less intrusive while retaining its function, I am happy to address it per-case.

> But given the current code, I can imagine what the challenges would be.

The main challenge is umu's downloads trying hard to do downloads in parallel. But to resolve the runtime requirement, the tool's manifest needs to be available and so forth. I made a few decisions this way because I explicitly did not want to touch the downloading part of umu.

The reason `umu-sniper/soldier/streamrt4` thin compat tools and codenames were made is because of how umu is structured. Instead of making more and more changes, I decided to provide umu's downloads with something they expect and be done with it.

In any case, this is now a solved issue, we have more than enough time to shape it up as long as I retains the current feature set.

2025-11-22 21:35 UTC, R1kaB3rN commented on docs/umu.1.scd
As previously stated:

> Users currently expect the value to be associated with Proton, not a token like umu-scout.

A change to the interface by extending `PROTONPATH` with tokens that are not related to Proton is a blocking issue for me that I feel strongly about and want for it to be stable. Until that is addressed, I will not look into this pull request any further. In the mean time, you can ask another maintainer for feedback/review who may/may not have different thoughts on this aspect.

My preference here is to have a new environment variable for this feature, and depending on the input, umu-launcher will switch to a different strategy where it would resolve all of the needed compatibility tools then build the command line sequence derived from all of the toolmanifest.vdf's from them. Clients such as Heroic Games Launcher would then be responsible to opt into the new feature to support use cases such as running old native Linux games, and can rest assured that the current interface is stable and is still as expected.

2025-11-25 03:52 UTC, merged

2025-11-30 21:08 UTC, MattSturgeon commented
This seems to have introduced several test failures:
https://github.com/Open-Wine-Components/umu-launcher/actions/runs/19657645355/job/56297675312

2025-11-30 21:40 UTC, loathingKernel commented
The tests along with some of the feedback here has been addressed in https://github.com/Open-Wine-Components/umu-launcher/pull/574

2026-03-16 12:22 UTC, nicymike commented
@loathingKernel Hi!

I guess you introduced a regression with your commit "umu_run: use `steam-runtime-launch-client` to re-enter an active container" of this PR. I am using Lutris to install a GOG game and it fails with error code 36608. I guess the error has something to do with re-entering a non existing container. Steam is installed but not running.
Btw. latest main is still failing.

My system is:
```
OS: CachyOS Linux rolling n/a
Arch: x86_64
Kernel: 6.19.7-1-cachyos
Lutris Version: 0.5.22
Python Version: 3.14.3 (main, Feb 18 2026, 14:35:05) [GCC 15.2.1 20260209]
Desktop: KDE
Display Server: x11

```

```
Started initial process 19156 from /home/michael/.local/bin/umu-run /home/michael/.cache/lutris/download/dark-reign-expansion/gog/setup_dark_reign__rise_of_the_shadowhand_1.4_hotfix_(57028).exe /SP- /NOCANCEL
Start monitoring process.
[umu.__main__:78] DEBUG: HOME=/home/michael
[umu.__main__:78] DEBUG: LANG=de_DE.UTF-8
[umu.__main__:78] DEBUG: LC_ADDRESS=de_DE.UTF-8
[umu.__main__:78] DEBUG: LC_IDENTIFICATION=de_DE.UTF-8
[umu.__main__:78] DEBUG: LC_MEASUREMENT=de_DE.UTF-8
[umu.__main__:78] DEBUG: LC_MONETARY=de_DE.UTF-8
[umu.__main__:78] DEBUG: LC_NAME=de_DE.UTF-8
[umu.__main__:78] DEBUG: LC_NUMERIC=de_DE.UTF-8
[umu.__main__:78] DEBUG: LC_PAPER=de_DE.UTF-8
[umu.__main__:78] DEBUG: LC_TELEPHONE=de_DE.UTF-8
[umu.__main__:78] DEBUG: LC_TIME=de_DE.UTF-8
[umu.__main__:78] DEBUG: LOGNAME=michael
[umu.__main__:78] DEBUG: PATH=/home/michael/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/michael/.local/share/JetBrains/Toolbox/scripts
[umu.__main__:78] DEBUG: SHELL=/usr/bin/bash
[umu.__main__:78] DEBUG: USER=michael
[umu.__main__:78] DEBUG: XDG_DATA_DIRS=/home/michael/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
[umu.__main__:78] DEBUG: XDG_RUNTIME_DIR=/run/user/1000
[umu.__main__:78] DEBUG: SSH_AUTH_SOCK=/run/user/1000/ssh-agent.socket
[umu.__main__:78] DEBUG: CUDA_DISABLE_PERF_BOOST=1
[umu.__main__:78] DEBUG: DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
[umu.__main__:78] DEBUG: DEBUGINFOD_URLS=https://debuginfod.archlinux.org https://debuginfod.cachyos.org 
[umu.__main__:78] DEBUG: DESKTOP_SESSION=/usr/share/xsessions/plasmax11.desktop
[umu.__main__:78] DEBUG: DISPLAY=:0
[umu.__main__:78] DEBUG: GTK2_RC_FILES=/etc/gtk-2.0/gtkrc:/home/michael/.gtkrc-2.0:/home/michael/.config/gtkrc-2.0
[umu.__main__:78] DEBUG: GTK3_MODULES=xapp-gtk3-module
[umu.__main__:78] DEBUG: GTK_MODULES=canberra-gtk-module
[umu.__main__:78] DEBUG: GTK_RC_FILES=/etc/gtk/gtkrc:/home/michael/.gtkrc:/home/michael/.config/gtkrc
[umu.__main__:78] DEBUG: ICEAUTHORITY=/run/user/1000/iceauth_LfIEMH
[umu.__main__:78] DEBUG: KDE_APPLICATIONS_AS_SCOPE=1
[umu.__main__:78] DEBUG: KDE_FULL_SESSION=true
[umu.__main__:78] DEBUG: KDE_SESSION_UID=1000
[umu.__main__:78] DEBUG: KDE_SESSION_VERSION=6
[umu.__main__:78] DEBUG: MAIL=/var/spool/mail/michael
[umu.__main__:78] DEBUG: MOTD_SHOWN=pam
[umu.__main__:78] DEBUG: PAM_KWALLET5_LOGIN=/run/user/1000/kwallet5.socket
[umu.__main__:78] DEBUG: PWD=/home/michael
[umu.__main__:78] DEBUG: QT_QPA_PLATFORM=xcb
[umu.__main__:78] DEBUG: SESSION_MANAGER=local/michael-pc:@/tmp/.ICE-unix/1849,unix/michael-pc:/tmp/.ICE-unix/1849
[umu.__main__:78] DEBUG: XAUTHORITY=/run/user/1000/xauth_ZUpZzo
[umu.__main__:78] DEBUG: XDG_CONFIG_DIRS=/home/michael/.config/kdedefaults:/etc/xdg
[umu.__main__:78] DEBUG: XDG_CURRENT_DESKTOP=KDE
[umu.__main__:78] DEBUG: XDG_MENU_PREFIX=plasma-
[umu.__main__:78] DEBUG: XDG_SEAT=seat0
[umu.__main__:78] DEBUG: XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
[umu.__main__:78] DEBUG: XDG_SESSION_CLASS=user
[umu.__main__:78] DEBUG: XDG_SESSION_DESKTOP=KDE
[umu.__main__:78] DEBUG: XDG_SESSION_ID=2
[umu.__main__:78] DEBUG: XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session1
[umu.__main__:78] DEBUG: XDG_SESSION_TYPE=x11
[umu.__main__:78] DEBUG: XDG_VTNR=2
[umu.__main__:78] DEBUG: MANAGERPID=1735
[umu.__main__:78] DEBUG: MANAGERPIDFDID=1736
[umu.__main__:78] DEBUG: INVOCATION_ID=30098b67a3404352bdf97a4e38059d4e
[umu.__main__:78] DEBUG: JOURNAL_STREAM=9:34909
[umu.__main__:78] DEBUG: SYSTEMD_EXEC_PID=1867
[umu.__main__:78] DEBUG: MEMORY_PRESSURE_WATCH=/sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/session.slice/plasma-plasmashell.service/memory.pressure
[umu.__main__:78] DEBUG: MEMORY_PRESSURE_WRITE=c29tZSAyMDAwMDAgMjAwMDAwMAA=
[umu.__main__:78] DEBUG: DESKTOP_STARTUP_ID=michael-pc;1773661012;946732;1867_TIME366190
[umu.__main__:78] DEBUG: LANGUAGE=
[umu.__main__:78] DEBUG: QT_WAYLAND_RECONNECT=1
[umu.__main__:78] DEBUG: WEBKIT_DISABLE_DMABUF_RENDERER=1
[umu.__main__:78] DEBUG: PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
[umu.__main__:78] DEBUG: __GL_SHADER_DISK_CACHE=1
[umu.__main__:78] DEBUG: __GL_SHADER_DISK_CACHE_PATH=/home/michael/.cache/lutris/shaders/wine
[umu.__main__:78] DEBUG: WINEDEBUG=-all
[umu.__main__:78] DEBUG: DXVK_LOG_LEVEL=error
[umu.__main__:78] DEBUG: UMU_LOG=1
[umu.__main__:78] DEBUG: WINEARCH=win64
[umu.__main__:78] DEBUG: PROTONPATH=GE-Proton
[umu.__main__:78] DEBUG: WINE=/home/michael/.local/bin/umu-run
[umu.__main__:78] DEBUG: WINEPREFIX=/home/michael/Games/gog/dark-reign-expansion
[umu.__main__:78] DEBUG: WINEESYNC=1
[umu.__main__:78] DEBUG: WINEFSYNC=1
[umu.__main__:78] DEBUG: WINE_FULLSCREEN_FSR=1
[umu.__main__:78] DEBUG: DXVK_NVAPIHACK=0
[umu.__main__:78] DEBUG: DXVK_ENABLE_NVAPI=1
[umu.__main__:78] DEBUG: PROTON_BATTLEYE_RUNTIME=/home/michael/.local/share/lutris/runtime/battleye_runtime
[umu.__main__:78] DEBUG: PROTON_EAC_RUNTIME=/home/michael/.local/share/lutris/runtime/eac_runtime
[umu.__main__:78] DEBUG: PROTON_DXVK_D3D8=1
[umu.__main__:78] DEBUG: WINEDLLOVERRIDES=d3d10core,d3d11,d3d12,d3d12core,d3d8,d3d9,d3dcompiler_33,d3dcompiler_34,d3dcompiler_35,d3dcompiler_36,d3dcompiler_37,d3dcompiler_38,d3dcompiler_39,d3dcompiler_40,d3dcompiler_41,d3dcompiler_42,d3dcompiler_43,d3dcompiler_46,d3dcompiler_47,d3dx10,d3dx10_33,d3dx10_34,d3dx10_35,d3dx10_36,d3dx10_37,d3dx10_38,d3dx10_39,d3dx10_40,d3dx10_41,d3dx10_42,d3dx10_43,d3dx11_42,d3dx11_43,d3dx9_24,d3dx9_25,d3dx9_26,d3dx9_27,d3dx9_28,d3dx9_29,d3dx9_30,d3dx9_31,d3dx9_32,d3dx9_33,d3dx9_34,d3dx9_35,d3dx9_36,d3dx9_37,d3dx9_38,d3dx9_39,d3dx9_40,d3dx9_41,d3dx9_42,d3dx9_43,dxgi,nvapi,nvapi64,nvofapi64=n;winemenubuilder=
[umu.__main__:78] DEBUG: LUTRIS_GAME_UUID=bf484828-800e-4f8d-bc2f-edb8b1d1fb77
[umu.umu_run:789] INFO: umu-launcher version 1.2.9 (3.14.3 (main, Feb 18 2026, 14:35:05) [GCC 15.2.1 20260209])
[umu.umu_run:795] DEBUG: Connecting to '1.1.1.1'...
[umu.umu_run:721] DEBUG: PROTONPATH is codename 'GE-Proton', defaulting to 'sniper'
[umu.umu_run:109] INFO: No GAMEID set, using umu-default
[umu.umu_runtime:238] DEBUG: Local: /home/michael/.local/share/umu/steamrt3
[umu.umu_proton:84] DEBUG: Sending request to 'api.github.com'...
[umu.umu_runtime:280] DEBUG: Existing install detected
[umu.umu_runtime:281] DEBUG: Using container runtime 'steamrt3' aka 'sniper'
[umu.umu_runtime:282] DEBUG: Checking updates for 'steamrt3'...
[umu.umu_runtime:326] DEBUG: Sending request to 'repo.steampowered.com/steamrt3/images/latest-public-beta/VERSION.txt?version=5oMLDiNzbYGHL70buQmkqw' for 'VERSION.txt'...
[umu.umu_proton:590] DEBUG: PROTONPATH not *-Latest, skipping
[umu.umu_proton:476] INFO: GE-Proton is up to date
[umu.umu_runtime:413] DEBUG: Acquiring file lock '/home/michael/.local/share/umu/umu.lock'...
[umu.umu_runtime:415] DEBUG: Acquired file lock '/home/michael/.local/share/umu/umu.lock'
[umu.umu_runtime:420] DEBUG: Released file lock '/home/michael/.local/share/umu/umu.lock'
[umu.umu_runtime:335] INFO: steamrt3 is up to date
[umu.umu_run:929] DEBUG: WINEPREFIX=/home/michael/Games/gog/dark-reign-expansion
[umu.umu_run:929] DEBUG: GAMEID=umu-default
[umu.umu_run:929] DEBUG: PROTON_CRASH_REPORT_DIR=/tmp/umu_crashreports
[umu.umu_run:929] DEBUG: PROTONPATH=/home/michael/.local/sh [...]

2026-03-16 12:28 UTC, loathingKernel commented
@nicymike This issue with lutris installers should fixed by https://github.com/Open-Wine-Components/umu-launcher/pull/633

2026-03-16 12:39 UTC, nicymike commented
@loathingKernel I tested your branch and installation with Lutris is working fine again. Thank you for your work.

I hope it will be merged soon because CachyOS maintainers are currently using main branch to build umu-launcher. Because of this I am affected by this bug.

2026-03-16 13:07 UTC, loathingKernel commented
@nicymike I had updated the CachyOS pkgbuild but it's not the repos yet. From your logs I saw that you are using a user-local version of `umu-run` in both cases, so I didn't think to mention that.

2026-03-16 18:48 UTC, nicymike commented
@loathingKernel Thank you.
Yes, for the tests I only used user-local versions but I first ran into the issue with the version from the repos:
- 1.3.0-2 was working
- 13.0-4 and up failed with the error code mentioned above